# Config file for automatic testing at travis-ci.org

language: python

matrix:
    include:
        - python: 2.7
          env: DJANGO=django==1.4.*
        - python: 2.7
          env: DJANGO=django==1.6.*
        - python: 2.7
          env: DJANGO=django==1.7.*
        - python: 2.7
          env: DJANGO=django==1.8.*

        - python: 3.3
          env: DJANGO=django==1.6.*
        - python: 3.3
          env: DJANGO=django==1.7.*
        - python: 3.3
          env: DJANGO=django==1.8.*

        - python: 3.4
          env: DJANGO=django==1.7.*
        - python: 3.4
          env: DJANGO=django==1.8.*

before_install:
  - pip install coveralls

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: pip install -r requirements-test.txt

# command to run tests using coverage, e.g. python setup.py test
script: coverage run --source cflatpages runtests.py

after_success:
  - coveralls

before_script:
  - flake8 . --config=.flake8
